<?php
/**
 * COLORJET ERP - Web Installer
 * Run this ONCE to set up the database and create config.php
 * DELETE or protect this file after installation!
 */

$step   = (int)($_GET['step'] ?? 1);
$errors = [];
$info   = [];

// Security: If already installed, require auth
if (file_exists(__DIR__ . '/config.php')) {
    require_once __DIR__ . '/config.php';
    // Allow reinstall with secret
    if (($_GET['secret'] ?? '') !== 'reinstall_colorjet') {
        die('<div style="font-family:sans-serif;text-align:center;padding:60px"><h2>✅ Already Installed</h2><p>COLORJET ERP is already installed. <a href="login.php">Go to Login</a></p><p><small>To reinstall, access install.php?secret=reinstall_colorjet</small></p></div>');
    }
}

// Check requirements
function checkRequirements(): array {
    $checks = [];
    $checks[] = ['PHP >= 8.0', version_compare(PHP_VERSION, '8.0', '>='), PHP_VERSION];
    $checks[] = ['PDO Extension', extension_loaded('pdo'), extension_loaded('pdo') ? 'Loaded' : 'Missing'];
    $checks[] = ['PDO MySQL', extension_loaded('pdo_mysql'), extension_loaded('pdo_mysql') ? 'Loaded' : 'Missing'];
    $checks[] = ['JSON Extension', extension_loaded('json'), extension_loaded('json') ? 'Loaded' : 'Missing'];
    $checks[] = ['mbstring Extension', extension_loaded('mbstring'), extension_loaded('mbstring') ? 'Loaded' : 'Missing'];
    $checks[] = ['OpenSSL Extension', extension_loaded('openssl'), extension_loaded('openssl') ? 'Loaded' : 'Missing'];
    $checks[] = ['Writable uploads/', is_writable(__DIR__ . '/uploads/'), is_writable(__DIR__ . '/uploads/') ? 'Writable' : 'Not writable'];
    $checks[] = ['Writable backups/', is_writable(__DIR__ . '/backups/'), is_writable(__DIR__ . '/backups/') ? 'Writable' : 'Not writable'];
    $checks[] = ['Schema file exists', file_exists(__DIR__ . '/database/schema.sql'), 'OK'];
    return $checks;
}

if ($step === 2 && $_SERVER['REQUEST_METHOD'] === 'POST') {
    $db_host    = trim($_POST['db_host'] ?? 'localhost');
    $db_port    = trim($_POST['db_port'] ?? '3306');
    $db_name    = trim($_POST['db_name'] ?? '');
    $db_user    = trim($_POST['db_user'] ?? '');
    $db_pass    = $_POST['db_pass'] ?? '';
    $app_url    = rtrim(trim($_POST['app_url'] ?? ''), '/');
    $app_key    = bin2hex(random_bytes(16));

    if (!$db_name || !$db_user) $errors[] = 'Database name and username are required.';

    if (!$errors) {
        try {
            $dsn = "mysql:host=$db_host;port=$db_port;charset=utf8mb4";
            $pdo = new PDO($dsn, $db_user, $db_pass, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);

            // Create database if not exists
            $pdo->exec("CREATE DATABASE IF NOT EXISTS `$db_name` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
            $pdo->exec("USE `$db_name`");

            // Import schema
            $schema = file_get_contents(__DIR__ . '/database/schema.sql');
            // Split by semicolons and execute
            $statements = array_filter(array_map('trim', explode(';', $schema)));
            foreach ($statements as $sql) {
                if ($sql && !str_starts_with($sql, '--')) {
                    try { $pdo->exec($sql); } catch (PDOException $e) { /* Allow errors for IF NOT EXISTS */ }
                }
            }

            // Write config.php
            $config = <<<PHP
<?php
// COLORJET ERP - Configuration
// Auto-generated by installer on {$_SERVER['SERVER_NAME']} · {date('Y-m-d H:i:s')}

define('DB_HOST',    '$db_host');
define('DB_PORT',    '$db_port');
define('DB_NAME',    '$db_name');
define('DB_USER',    '$db_user');
define('DB_PASS',    '$db_pass');
define('DB_CHARSET', 'utf8mb4');

define('APP_NAME',     'COLORJET ERP');
define('APP_URL',      '$app_url');
define('APP_ENV',      'production');
define('APP_DEBUG',    false);
define('APP_KEY',      '$app_key');
define('APP_TIMEZONE', 'Asia/Dhaka');

define('SESSION_NAME',     'COLORJET_ERP');
define('SESSION_LIFETIME', 480);
define('CSRF_TOKEN_NAME',  'cj_csrf');

define('UPLOAD_PATH',      __DIR__ . '/uploads/');
define('UPLOAD_MAX_SIZE',  10485760);
define('ALLOWED_FILE_TYPES', ['jpg','jpeg','png','gif','pdf','doc','docx','xls','xlsx','csv','txt']);

define('LOG_PATH',    __DIR__ . '/logs/');
define('BACKUP_PATH', __DIR__ . '/backups/');

define('DEFAULT_CURRENCY',        'BDT');
define('DEFAULT_CURRENCY_SYMBOL', '৳');
PHP;

            file_put_contents(__DIR__ . '/config.php', $config);
            header('Location: install.php?step=3');
            exit;
        } catch (PDOException $e) {
            $errors[] = 'Database connection failed: ' . $e->getMessage();
        } catch (Exception $e) {
            $errors[] = 'Installation error: ' . $e->getMessage();
        }
    }
}

?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>COLORJET ERP — Installer</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
  <style>
    body { background: linear-gradient(135deg, #0d6efd 0%, #0ea5e9 100%); min-height: 100vh; }
    .installer-card { background: #fff; border-radius: 20px; padding: 40px; max-width: 700px; margin: 40px auto; box-shadow: 0 20px 60px rgba(0,0,0,0.2); }
    .step-badge { background: #0d6efd; color: #fff; width: 40px; height: 40px; border-radius: 50%; display: inline-flex; align-items: center; justify-content: center; font-weight: bold; margin-right: 10px; }
    .check-ok { color: #22c55e; } .check-fail { color: #ef4444; }
    .brand { font-size: 28px; font-weight: 800; color: #0d6efd; letter-spacing: 1px; margin-bottom: 4px; }
  </style>
</head>
<body>
<div class="container">
  <div class="installer-card">
    <div class="text-center mb-4">
      <div class="brand"><i class="fas fa-print me-2"></i>COLORJET ERP</div>
      <div class="text-muted">Web Application Installer</div>
    </div>

    <!-- Steps -->
    <div class="d-flex justify-content-center gap-4 mb-4">
      <?php foreach (['Requirements' => 1, 'Database' => 2, 'Complete' => 3] as $label => $s): ?>
      <div class="text-center">
        <div class="step-badge <?= $step >= $s ? '' : 'opacity-50' ?>"><?= $s ?></div>
        <div class="small <?= $step === $s ? 'fw-bold' : 'text-muted' ?>"><?= $label ?></div>
      </div>
      <?php endforeach; ?>
    </div>

    <?php if ($step === 1): ?>
    <!-- Step 1: Requirements -->
    <h4><span class="step-badge">1</span>System Requirements</h4>
    <table class="table mt-3">
      <?php
      $checks  = checkRequirements();
      $allPass = true;
      foreach ($checks as [$name, $pass, $value]):
        if (!$pass) $allPass = false;
      ?>
      <tr>
        <td><?= $name ?></td>
        <td><?= h($value) ?></td>
        <td><?= $pass ? '<i class="fas fa-check-circle check-ok"></i>' : '<i class="fas fa-times-circle check-fail"></i>' ?></td>
      </tr>
      <?php endforeach; ?>
    </table>
    <?php if (!$allPass): ?>
    <div class="alert alert-danger">Some requirements are not met. Please fix them before continuing.</div>
    <?php else: ?>
    <div class="alert alert-success"><i class="fas fa-check-circle me-2"></i>All requirements met!</div>
    <a href="install.php?step=2" class="btn btn-primary btn-lg w-100">Continue to Database Setup →</a>
    <?php endif; ?>

    <?php elseif ($step === 2): ?>
    <!-- Step 2: Database -->
    <h4><span class="step-badge">2</span>Database Configuration</h4>
    <?php if ($errors): ?><div class="alert alert-danger"><?= implode('<br>', array_map('h', $errors)) ?></div><?php endif; ?>
    <form method="POST" action="install.php?step=2">
      <div class="row g-3">
        <div class="col-md-8"><label class="form-label">Database Host</label><input type="text" name="db_host" class="form-control" value="localhost" required></div>
        <div class="col-md-4"><label class="form-label">Port</label><input type="text" name="db_port" class="form-control" value="3306"></div>
        <div class="col-md-6"><label class="form-label">Database Name <span class="text-danger">*</span></label><input type="text" name="db_name" class="form-control" value="colorjet_erp" required></div>
        <div class="col-md-6"><label class="form-label">Database Username <span class="text-danger">*</span></label><input type="text" name="db_user" class="form-control" required></div>
        <div class="col-12"><label class="form-label">Database Password</label><input type="password" name="db_pass" class="form-control" placeholder="Leave blank if no password"></div>
        <div class="col-12"><label class="form-label">Application URL</label><input type="text" name="app_url" class="form-control" value="https://erp.colorjetbd.com" required><div class="form-text">No trailing slash. Example: https://erp.colorjetbd.com</div></div>
      </div>
      <div class="alert alert-warning mt-3"><i class="fas fa-exclamation-triangle me-2"></i>This will create the database tables and default admin user. Existing tables will NOT be dropped.</div>
      <button type="submit" class="btn btn-primary btn-lg w-100 mt-3"><i class="fas fa-database me-2"></i>Install Database</button>
    </form>

    <?php elseif ($step === 3): ?>
    <!-- Step 3: Complete -->
    <div class="text-center">
      <div style="font-size:80px;color:#22c55e"><i class="fas fa-check-circle"></i></div>
      <h3 class="mt-3">Installation Complete!</h3>
      <p class="text-muted">COLORJET ERP has been successfully installed.</p>
      <div class="alert alert-info text-start mt-3">
        <h6><i class="fas fa-key me-2"></i>Default Login Credentials:</h6>
        <table class="table table-sm mb-0">
          <tr><td>Admin:</td><td><strong>admin@colorjetbd.com</strong></td><td>password: <code>password</code></td></tr>
          <tr><td>Owner:</td><td><strong>owner@colorjetbd.com</strong></td><td>password: <code>password</code></td></tr>
        </table>
      </div>
      <div class="alert alert-danger">
        <i class="fas fa-exclamation-triangle me-2"></i>
        <strong>Security!</strong> Change passwords immediately after first login!<br>
        Also delete or restrict access to <code>install.php</code>
      </div>
      <a href="login.php" class="btn btn-primary btn-lg w-100">Go to Login →</a>
    </div>
    <?php endif; ?>
  </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
